version: '2.3'
services:
  dbmate:
    build:
      context: .
      target: build
    volumes:
      - .:/go/src/github.com/amacneil/dbmate
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "status", "-proot"]

  postgres:
    image: postgres
    healthcheck:
      test: ["CMD", "pg_isready"]
