version: '2.3'
services:
  dbmate:
    build:
      context: .
      target: build
    depends_on:
      - mysql
      - postgres
      - oracle
    environment:
      MYSQL_URL: mysql://root:root@mysql/dbmate
      POSTGRESQL_URL: postgres://postgres:postgres@postgres/dbmate?sslmode=disable
      ORACLE_URL: oracle://system:oracle@oracle:1521/ORCLCDB

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres

  oracle:
    image: csuriano/loki:orase1930
