version: '2.3'
services:
  dbmate:
    build:
      context: .
      target: build
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "status", "-proot"]

  postgres:
    image: postgres:9.6
    healthcheck:
      test: ["CMD", "pg_isready"]
