version: '2.3'
services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/src
    depends_on:
      - mysql
      - postgres
      - clickhouse
    environment:
      MYSQL_URL: mysql://root:root@mysql/dbmate
      POSTGRESQL_URL: postgres://postgres:postgres@postgres/dbmate?sslmode=disable
      CLICKHOUSE_URL: clickhouse://clickhouse:9000?database=dbmate

  dbmate:
    build:
      context: .
      target: release

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: postgres

  clickhouse:
    image: yandex/clickhouse-server:19.16
